// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdnr39al7ppVHNhgYm5u_Nqzc03pdSw50',
    appId: '1:45362976287:web:163956adb422096b7fe72a',
    messagingSenderId: '45362976287',
    projectId: 'ecommarce2025',
    authDomain: 'ecommarce2025.firebaseapp.com',
    storageBucket: 'ecommarce2025.firebasestorage.app',
    measurementId: 'G-5SP5SL7D63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVGr6z7swU-7pm6_CSJZvi3eaUj-3-ec',
    appId: '1:45362976287:android:2104efd1ff92a37c7fe72a',
    messagingSenderId: '45362976287',
    projectId: 'ecommarce2025',
    storageBucket: 'ecommarce2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFGgsj8bquVmqtxOefibvDgr2LXANpgXo',
    appId: '1:45362976287:ios:f0011bcca898a6bc7fe72a',
    messagingSenderId: '45362976287',
    projectId: 'ecommarce2025',
    storageBucket: 'ecommarce2025.firebasestorage.app',
    androidClientId: '45362976287-pg3sfhbnvs26mfgnacjbv38lb69uhbcg.apps.googleusercontent.com',
    iosClientId: '45362976287-0o9f3ifegouasnad0vhus5689e7vkfmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommarceproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFGgsj8bquVmqtxOefibvDgr2LXANpgXo',
    appId: '1:45362976287:ios:f0011bcca898a6bc7fe72a',
    messagingSenderId: '45362976287',
    projectId: 'ecommarce2025',
    storageBucket: 'ecommarce2025.firebasestorage.app',
    androidClientId: '45362976287-pg3sfhbnvs26mfgnacjbv38lb69uhbcg.apps.googleusercontent.com',
    iosClientId: '45362976287-0o9f3ifegouasnad0vhus5689e7vkfmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommarceproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdnr39al7ppVHNhgYm5u_Nqzc03pdSw50',
    appId: '1:45362976287:web:f4e9c370cff0a67a7fe72a',
    messagingSenderId: '45362976287',
    projectId: 'ecommarce2025',
    authDomain: 'ecommarce2025.firebaseapp.com',
    storageBucket: 'ecommarce2025.firebasestorage.app',
    measurementId: 'G-14H97KWVWL',
  );

}